### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by 0xdevalias** [VirtueSecurity/aws-extender-cli#1]
It would be cool to have Python 3 support, and at the very least, a note in the README that 2.x is required currently.

```
⇒  python --version
Python 3.5.2
```

```
python aws_extender_cli.py -h
  File "aws_extender_cli.py", line 497
    print ''.join(issues).strip()
           ^
SyntaxError: invalid syntax
```

**Comment by 0xSobky** [comment]
Thanks @alias1. A pull request that resolves this issue will be merged shortly.
